Fixed (sorta) http://nagoya.apache.org/bugzilla/show_bug.cgi?id=11781. That bug turned out to be user error, but the user was getting a very unfriendly NullPointerException.  Now at least AXIS will tell the user:
java.io.IOException: No support for attachments.


git-svn-id: https://svn.apache.org/repos/asf/webservices/axis1/trunk/java@247935 13f79535-47bb-0310-9956-ffa450edef68